import type { Metadata } from "next";
import { Noto_Sans_TC } from "next/font/google";
import "./globals.scss";
import SWRegister from "@/components/SWRegister";

const notoSansTC = Noto_Sans_TC({
  variable: "--font-noto-sans-tc",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body> */}
      <body className={`${notoSansTC.variable}`}>
        {children}
        <SWRegister />
      </body>
    </html>
  );
}
