import type { Metadata } from "next";
import { Noto_Sans_TC } from "next/font/google";
import { headers } from "next/headers";

import getCurrentUserDataCache from "@/cache/user/getCurrentUserData";

import SWRegister from "@/components/SWRegister";
import AutoRefresh from "@/components/AutoRefresh";
import NavigateBar from "@/components/NavigateBar";

import checkIsMobile from "@/utils/detectmobilebrowser";

import "./globals.scss";
import UserDataContextProvider from "@/context/userDataContext";

const notoSansTC = Noto_Sans_TC({
    variable: "--font-noto-sans-tc",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: {
        icon: {
            url: "/favicon.ico",
            type: "image/x-icon",
        },
        other: [
            {
                url: "/favicon.png",
                type: "image/png",
            },
            {
                url: "/favicon.svg",
                type: "image/svg+xml",
            }
        ]
    },
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const headerList = await headers();
    const isMobile = checkIsMobile(headerList.get("user-agent") || "");

    let userData = null;
    try { userData = await getCurrentUserDataCache(); }
    catch { }

    return <html lang="en">
        <body className={`${notoSansTC.className}`}>
            <UserDataContextProvider userData={userData}>
                {children}
            </UserDataContextProvider>
            <NavigateBar isMobile={isMobile} />
            <SWRegister />
            <AutoRefresh />
            <script>0</script>
        </body>
    </html>;
}
